/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_themkr_nativeeffect_NativeMethods */

#ifndef _Included_com_themkr_nativeeffect_NativeMethods
#define _Included_com_themkr_nativeeffect_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_themkr_nativeeffect_NativeMethods
 * Method:    getConventionalEffectedBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;F[F)V
 */
JNIEXPORT void JNICALL Java_com_themkr_nativeeffect_NativeMethods_getConventionalEffectedBitmap
  (JNIEnv *, jclass, jobject, jobject, jfloat, jfloatArray);

/*
 * Class:     com_themkr_nativeeffect_NativeMethods
 * Method:    getColorEffectedBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;F[F)V
 */
JNIEXPORT void JNICALL Java_com_themkr_nativeeffect_NativeMethods_getColorEffectedBitmap
  (JNIEnv *, jclass, jobject, jobject, jfloat, jfloatArray);

/*
 * Class:     com_themkr_nativeeffect_NativeMethods
 * Method:    getInversedColorEffectedBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;FI)V
 */
JNIEXPORT void JNICALL Java_com_themkr_nativeeffect_NativeMethods_getInversedColorEffectedBitmap
  (JNIEnv *, jclass, jobject, jobject, jfloat, jint);

/*
 * Class:     com_themkr_nativeeffect_NativeMethods
 * Method:    getOverLayBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_themkr_nativeeffect_NativeMethods_getOverLayBitmap
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
