package com.adroitstudio.photocollage;

import android.os.Environment;

public interface Constants {
	int INVALID_LAYOUT = -9999;
	String EXTERNAL_DRIVE_PATH = Environment.getExternalStorageDirectory().toString() + "/PhotoCollage";
	String ASSETS_SHAPE = "shapes";
	String ASSETS_SHAPE_THUMBNAIL = "shape_thumb";
	String ASSETS_BACKGROUNDS = "collage_bg";
	String ASSETS_DEFAULT_BGS = "default_bgs";
	String ASSETS_SHAPE_UTILS = "shape_utils";
	String ASSETS_COLLAGE_RATIO = "collage_ratio";
	String ASSETS_CLIP_ARTS = "clip_arts";

	String ASSETS_GRID_1 = "grids/pic1";
	String ASSETS_GRID_2 = "grids/pic2";
	String ASSETS_GRID_3 = "grids/pic3";
	String ASSETS_GRID_4 = "grids/pic4";
	String ASSETS_GRID_5 = "grids/pic5";
	String ASSETS_GRID_6 = "grids/pic6";
	String ASSETS_GRID_7 = "grids/pic7";
	String ASSETS_GRID_8 = "grids/pic8";
	String ASSETS_GRID_9 = "grids/pic9";
	String[] ASSETS_GRID = { ASSETS_GRID_1, ASSETS_GRID_2, ASSETS_GRID_3, ASSETS_GRID_4, ASSETS_GRID_5, ASSETS_GRID_6, ASSETS_GRID_7, ASSETS_GRID_8, ASSETS_GRID_9 };

	// COSTANTS FOR IMAGE LOCATION
	int SOURCE_APPLICATION = 101;
	int SOURCE_DEVICE = 102;

	// CONSTANTS FOR IMAGE TYPE
	int IMAGE_TYPE_FULL_SIZE = 10001;
	int IMAGE_TYPE_THUMBNAIL_MICRO = 10002;
	int IMAGE_TYPE_SIZE_1234 = 10003;
	int IMAGE_TYPE_SIZE_56789 = 10004;

	// CONSTANTS FOR COLLAGE RATIO
	int COLLAGE_RATIO_1_1 = 1001;
	int COLLAGE_RATIO_1_2 = 1002;
	int COLLAGE_RATIO_2_1 = 1003;
	int COLLAGE_RATIO_2_3 = 1004;
	int COLLAGE_RATIO_3_2 = 1005;

	// COLLAGE TYPE
	int COLLAGE_TYPE_SHAPE = 1001;
	int COLLAGE_TYPE_FREE = 1002;
	int COLLAGE_TYPE_FIXED = 1003;

	int LAYOUT_A1 = 0;
	int LAYOUT_A2 = 1;
	int LAYOUT_A3 = 2;
	int LAYOUT_A4 = 3;
	int LAYOUT_A5 = 4;
	int LAYOUT_A6 = 5;
	int LAYOUT_A7 = 6;
	int LAYOUT_A8 = 7;
	int LAYOUT_A9 = 8;
	int LAYOUT_AA0 = 9;
	int LAYOUT_AA1 = 10;
	int LAYOUT_AA2 = 11;
	int LAYOUT_AA3 = 12;
	int LAYOUT_AA4 = 13;
	int LAYOUT_AA5 = 14;
	int LAYOUT_AA6 = 15;
	int LAYOUT_AA7 = 16;
	int LAYOUT_AA8 = 17;
	int LAYOUT_AA9 = 18;
	int LAYOUT_AAA0 = 19;
	int LAYOUT_AAA1 = 20;
	int LAYOUT_AAA2 = 21;
	int LAYOUT_AAA3 = 22;
	int LAYOUT_AAA4 = 23;
	int LAYOUT_AAA5 = 24;
	int LAYOUT_AAA6 = 25;
	int LAYOUT_AAA7 = 26;
	int LAYOUT_AAA8 = 27;
	int LAYOUT_AAA9 = 28;
	int LAYOUT_AAAA0 = 29;
	int LAYOUT_AAAA1 = 30;
	int LAYOUT_AAAA2 = 31;
	int LAYOUT_AAAA3 = 32;
	int LAYOUT_AAAA4 = 33;

	int LAYOUT[] = { LAYOUT_A1, LAYOUT_A2, LAYOUT_A3, LAYOUT_A4, LAYOUT_A5, LAYOUT_A6, LAYOUT_A7, LAYOUT_A8, LAYOUT_A9, LAYOUT_AA0, LAYOUT_AA1, LAYOUT_AA2, LAYOUT_AA3, LAYOUT_AA4, LAYOUT_AA5, LAYOUT_AA6, LAYOUT_AA7, LAYOUT_AA8, LAYOUT_AA9, LAYOUT_AAA0, LAYOUT_AAA1, LAYOUT_AAA2, LAYOUT_AAA3, LAYOUT_AAA4, LAYOUT_AAA5, LAYOUT_AAA6, LAYOUT_AAA7, LAYOUT_AAA8, LAYOUT_AAA9, LAYOUT_AAAA0, LAYOUT_AAAA1, LAYOUT_AAAA2, LAYOUT_AAAA3, LAYOUT_AAAA4 };

}
